name: Test and Coverage

# main ブランチへの push と PR 作成・更新時にワークフローを起動する例
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    steps:
      # リポジトリのソースコードをチェックアウト
      - name: Check out repository
        uses: actions/checkout@v3

      # Node.js のバージョン設定
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # pnpm のセットアップ
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      # 依存パッケージをインストール (pnpm を使用)
      - name: Install dependencies
        run: pnpm install
        
      # TypeScript の型チェック
      - name: Type check
        run: pnpm run tsc:api
        
      # ESLint によるコード品質チェック
      - name: Lint
        run: |
          pnpm install --save-dev eslint eslint-config-next
          pnpm run lint

      # ユニットテスト実行
      - name: Run unit tests
        run: pnpm run test -- tests/unit/

      # テスト＆カバレッジ実行
      - name: Run tests with coverage
        run: pnpm run coverage

      # カバレッジレポートのアップロード
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN || '' }}
          directory: ./coverage/
          fail_ci_if_error: false
